### PR TITLE
JSF trying to load DTD over the network

### PR DESCRIPTION
**Pull request by moulalis**
Signed-off-by: Moulali Shikalwadi <mshikalw@redhat.com>

 issue: eclipse-ee4j/mojarra#4699

### CODE REVIEW

**Comment by moulalis** [comment]
Can modify the change to introduce a context parameter to control this if you prefer.

**Comment by spyrkob** [comment]
@arjantijms could you take a look at this please?

**Comment by arjantijms** [comment]
> could you take a look at this please?

The code seems fine, but the ECA check fails unfortunately. That has to be fixed before this can be merged.

**Comment by spyrkob** [comment]
Thanks @arjantijms!

**Comment by moulalis** [comment]
> > could you take a look at this please?
> 
> The code seems fine, but the ECA check fails unfortunately. That has to be fixed before this can be merged.

**Comment by moulalis** [comment]
@arjantijms , @spyrkob ,
I have Singed the ECA. Let me know is anything else is needed.
Thanks.

**Comment by arjantijms** [comment]
> I have Singed the ECA. Could you please run ECA check. Let me know if anything else is needed.

The check can't be run on demand, but your force pushing has triggered it again as you might have seen, and now it passes :)

**Comment by arjantijms** [comment]
A tiny tiny comment is that in newer code we usually try to avoid abbreviations that aren't clear by themselves, like "dbf" here. But it's not a blocker. Thanks a bunch for your contribution!

**Comment by erickdeoliveiraleal** [comment]
this pull request should hava a backport to 2.3 branch

**Pull request merged**
