### PR TITLE
Move back weld reinit from ConfigureListener into FacesInitializer

### PR DESCRIPTION
**Pull request by BalusC**
https://github.com/eclipse-ee4j/mojarra/issues/5321

### CODE REVIEW

**Comment by mnriem** [comment]
LGTM

**Review by mnriem — APPROVED** [review]

**Comment by mnriem** [comment]
@BalusC Can you please file an issue so we can tie all the ports (4.0, 4.1 and 5.0) to the issue?

**Comment by arjantijms** [comment]
Lgtm, though I really wish we could somehow persuade the two CDI spec leads that Faces needs a universal solution for this in the CDI spec.

**Comment by melloware** [comment]
@arjantijms if there is a CDI ticket open somewhere about this issue I am happy to go upvote it and have my friends upvote as well 😄

**Comment by BalusC** [comment]
> @BalusC Can you please file an issue so we can tie all the ports (4.0, 4.1 and 5.0) to the issue?

issue is already linked in 1st comment

**Pull request merged**
