### PR TITLE
fix NPE if getResourcePaths return null

### PR DESCRIPTION
**Pull request by zfqjava**
java.lang.NullPointerException: Cannot invoke "java.util.Collection.size()" because "c" is null
                at java.base/java.util.ArrayDeque.addAll(ArrayDeque.java:322)
                at com.sun.faces.application.resource.ResourcePathsIterator.visit(ResourcePathsIterator.java:67)
                at com.sun.faces.application.resource.ResourcePathsIterator.tryTake(ResourcePathsIterator.java:79)
                at com.sun.faces.application.resource.ResourcePathsIterator.hasNext(ResourcePathsIterator.java:51)

### CODE REVIEW

**Comment by codylerum** [comment]
Should `ExternalContext#getResourcePaths` be returning an empty set rather than a null?

https://jakarta.ee/specifications/platform/10/apidocs/jakarta/faces/context/externalcontext#getResourcePaths-java.lang.String-

**Comment by melloware** [comment]
Agreed this should return a new empty Stack if bill

**Comment by BalusC** [comment]
This is exactly how `ServletContext#getResourcePaths()` is implemented: https://jakarta.ee/specifications/platform/10/apidocs/jakarta/servlet/servletcontext#getResourcePaths(java.lang.String) The ExternalContext is merely a facade thereof.

We can of course deviate from this, but this is a breaking change and should be done in a major version only.

**Review by BalusC — APPROVED** [review]

**Comment by BalusC** [comment]
Note that this PR is made for master branch, not for 2.3/3.0/4.0. If this was not your original intent, adjust accordingly.

**Comment by BalusC** [comment]
No comment a week. Merging anyway.

**Pull request merged**
