### PR TITLE
ui:repeat clarification on attributes, such as offset and size

### PR DESCRIPTION
**Pull request by BalusC**
https://github.com/jakartaee/faces/issues/1713

cc @tandraschko

### CODE REVIEW

**Comment by mnriem** [comment]
LGTM. If it is targeted to only 5.0 is it maybe time to make UIRepeat go to the same package as the rest of the UI classes?

**Review by mnriem — APPROVED** [review]

**Comment by BalusC** [comment]
> If it is targeted to only 5.0 is it maybe time to make UIRepeat go to the same package as the rest of the UI classes?

`jakarta.faces.component.UIRepeat`? Sounds good to me. Should go via separate spec issue tho.

**Comment by tandraschko** [comment]
+1

**Comment by pizzi80** [comment]
+1 for everything :smiley:

**Comment by BalusC** [comment]
Associated TCK https://github.com/jakartaee/faces/pull/1852

**Comment by mnriem** [comment]
@BalusC Is this waiting on a review? Looks like the jakarta-faces side was done?

**Comment by BalusC** [comment]
I actually waited on a working TCK. But yeah, I'll just merge.

**Pull request merged**
