### PR TITLE
[#4431] NPE in ELFlash.get() on first request

### PR DESCRIPTION
**Pull request by spyrkob**
Possible fix for https://github.com/eclipse-ee4j/mojarra/issues/4431

### CODE REVIEW

**Comment by fjuma** [comment]
@spyrkob This one has a conflict that needs to be fixed. Thanks!

**Comment by fjuma** [comment]
Just FYI, this PR has been submitted against master but we'll also need this to be merged to the 2.3 branch.

**Comment by spyrkob** [comment]
Opened 2.3 PR https://github.com/eclipse-ee4j/mojarra/pull/4823.

btw. I think the test failures are caused by #4821

**Review by manorrock — APPROVED** [review]
Since this is a PR without a supplied test requesting additional reviewers.

Related PR is https://github.com/eclipse-ee4j/mojarra/pull/4823

**Review by arjantijms — APPROVED** [review]

**Pull request merged**
