### PR TITLE
#4642 Add BeanManager lookup fallback to CDI.current

### PR DESCRIPTION
**Pull request by christophs78**

### CODE REVIEW

**Comment by christophs78** [comment]
Migrated some code from MyFaces (https://github.com/apache/myfaces/blob/114fd7af5c42865c48ef0d98e185dd102e2b9395/impl/src/main/java/org/apache/myfaces/webapp/FacesInitializerImpl.java#L534) to Mojarra.

Can you merge this PR (targeted for 2.3) also into 3.0 and 4.0 or should i provide separate PR´s?

Not sure whether we still need the WELD-special-treatment:
`result = (BeanManager) applicationMap.get("org.jboss.weld.environment.servlet.javax.enterprise.inject.spi.BeanManager");`

IMO MyFaces does the JNDI-lookup a bit more structured. When you wish, i may port this part of to Mojarra too.

**Comment by christophs78** [comment]
Hm. We may do this without of reflections because JSF since 2.3 requires CDI.

**Review by melloware — APPROVED** [review]

**Comment by tandraschko** [comment]
at least you can do it without reflection in 4.0 but 2.3 may also be used with CDI 1.0

**Comment by BalusC** [comment]
But Mojarra is already doing that? https://github.com/eclipse-ee4j/mojarra/blob/8eb32a83c40c3666fa568a32ca450bbf1b63875d/impl/src/main/java/com/sun/faces/util/Util.java#L1572

**Comment by christophs78** [comment]
OK. Fixed but not released. Missed this detail.

**Comment by tandraschko** [comment]
Also fixed in 2.3 or only newer?

**Comment by christophs78** [comment]
Also fixed for 2.3.
(Analysed this issue with 2.3.16 and had tomatoes on my eyes when i did this PR.)

**Pull request closed without merging**
