### PR TITLE
Do not log ClientAbortException - 3.0

### PR DESCRIPTION
**Pull request by melloware**
Signed-off-by: melloware <mellowaredev@gmail.com>

### CODE REVIEW

**Comment by BalusC** [comment]
This PR was wrong. It was merged into master instead of 3.0.

I'll sort out via an upmerge.

**Comment by BalusC** [comment]
Done: https://github.com/eclipse-ee4j/mojarra/commit/7a96cc365849f7db94a16ec2828e211196542435

**Comment by melloware** [comment]
Sorry about that.  Sometimes gets confusing with 3 branches!

**Comment by arjantijms** [comment]
> Sorry about that. Sometimes gets confusing with 3 branches!

After EE 10 is released we might wanna do a final release for 3.x and then close the 3.0 branch. It seems like not many people are that interested in it, and most interest is for 2.3.

**Comment by melloware** [comment]
I totally agree about 3.x.  I support that 100% as 2.3 and 4.0 will have the most usage.

**Pull request merged**
