### PR TITLE
Add back id attribute to VDL of h:head and h:body

### PR DESCRIPTION
**Pull request by BalusC**
https://github.com/jakartaee/faces/issues/1760
- Add back id attribute to VDL of h:head and h:body
- fix HeadRenderer to only output it when actually specified
- fix BodyRenderer to only output it when HTML5 doctype is used""

### CODE REVIEW

**Comment by BalusC** [comment]
Ran entire tck localhost as well, all green.

**Review by melloware — APPROVED** [review]

**Comment by BalusC** [comment]
Thomas can you review at least the spec change in taglib? https://github.com/eclipse-ee4j/mojarra/pull/5186/files#diff-a977313af2132f4b6dc25adc6bd8719a6822c5ae62ef547d1d7d82bbdc0baab3

**Comment by BalusC** [comment]
@tandraschko can you please review?

**Comment by melloware** [comment]
I know he is on holiday but i think he is back sometime next week.

**Comment by tandraschko** [comment]
@BalusC i wonder why this was removed in general?

In MyFaces it looks like we always render the head/body id if specified by the user, doent matter if html5 or not

**Comment by BalusC** [comment]
It was accidentally removed, see also https://github.com/jakartaee/faces/issues/1760#issuecomment-1349635281

**Pull request merged**
