### PR TITLE
Fixes #5000 - Change Mojarra implementation artifactId to mojarra

### LINKED ISSUE #5000: Change Mojarra implementation artifactId to mojarra
Currently the maven coordinates of mojarra are:

```xml
<groupId>org.glassfish</groupId>
<artifactId>jakarta.faces</artifactId>
```

The comes from the RI days where the naming pattern was `[spec]-api` for the API jar, and `[spec]` for the implementation jar. As Mojarra is no longer the RI (there is no RI concept in Jakarta EE), implementations have been asked to move away from this pattern.

I would like to propose to use:

```xml
<groupId>org.glassfish.mojarra</groupId>
<artifactId>mojarra</artifactId>
```

### PR DESCRIPTION
**Pull request by mnriem**

### CODE REVIEW

**Comment by mnriem** [comment]
@arjantijms @BalusC Have a look

**Review by melloware — APPROVED** [review]

**Review by BalusC — APPROVED** [review]

**Comment by BalusC** [comment]
Can this also go in 4.1?

**Comment by mnriem** [comment]
@arjantijms What do you think? Personally I am fine holding off on this and only target it for 5.0

**Comment by BalusC** [comment]
Totally ok. Was just wondering.

**Pull request merged**
