### PR TITLE
forward port from 2.2.8 for bug 25419764: JSF WARNING UNABLE TO SAFEL…

### PR DESCRIPTION
**Pull request by spyrkob**
…Y DETERMINE WHICH FACTORYMANAGER INSTANCE TO USE.

Issue: #4660 

Signed-off-by: Bartosz Spyrko-Smietanko <spyrkob@gmail.com>

### CODE REVIEW

**Comment by spyrkob** [comment]
@arjantijms could you take a look at this PR please? It seems that commit has been missed during migration to eclipse repository.

**Comment by fjuma** [comment]
@spyrkob This one has a conflict that needs to be fixed. Thanks!

**Comment by fjuma** [comment]
Just FYI, this PR has been submitted against master but we'll also need this to be merged to the 2.3 branch.

**Comment by BalusC** [comment]
I'll sync up with 2.3 and 3.0

**Pull request merged**
