### PR TITLE
improve logging message for unresolved navigation outcome

### PR DESCRIPTION
**Pull request by codylerum**

### CODE REVIEW

**Comment by mnriem** [comment]
LGTM

**Comment by codylerum** [comment]
Would like to target to 4.0 if possible. I can create backports to 3 and 2.3 if desired otherwise I can just pick this up when I move to 4.0

**Review by arjantijms — APPROVED** [review]

**Comment by arjantijms** [comment]
Thanks! This should appear in the next 4.0.0 milestone.

**Comment by mnriem** [comment]
@codylerum Thanks for taking it all the way!

**Comment by codylerum** [comment]
@mnriem Happy to see Mojarra moving forward!

**Pull request merged**
