### PR TITLE
refactor: Java Security Ultimate Security Repo Scanner 2023

### PR DESCRIPTION
**Pull request by caytec**
Use this link to re-run the recipe: https://app.moderne.io/recipes/builder/TkgUEiqd7?organizationId=RWNsaXBzZSBGb3VuZGF0aW9u

### CODE REVIEW

**Comment by BalusC** [comment]
Point taken but code isn't DRY.

**Comment by BalusC** [comment]
Build is failing.

```
 Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project mojarra: Compilation failure
Error:  /home/runner/work/mojarra/mojarra/impl/src/main/java/com/sun/faces/util/Util.java:[282,31] unreported exception javax.xml.transform.TransformerConfigurationException; must be caught or declared to be thrown
```

Looks like this all is automated. I think I'll reject the PR and take at my own hands.

**Comment by BalusC** [comment]
Taking a second look, I'm wondering if it should really throw ISE and thus kill the app when a specific feature isn't supported by the JAXP impl? I see one feature using apache.org namespace which will clearly work on e.g. Xerces, but what if a non-apache-vended JAXP impl is used (frankly none comes to mind and Saxon is dead but it doesn't mean that it is impossible). What's the harm of just continuing?

**Comment by mnriem** [comment]
@BalusC Can this PR be closed out in favor of #5343

**Pull request closed without merging**
