### PR TITLE
Support for the Jakarta EE 11 M1 release

### PR DESCRIPTION
**Pull request by arjantijms**
Update dependencies to their M1 versions where applicable, and update code to support this.

Set release target to JDK 17, and removed some resulting warnings.

### CODE REVIEW

**Comment by arjantijms** [comment]
PR will be updated with expressly M1 once it's available.

**Comment by pzygielo** [comment]
https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#release - it's recognized since plugin 3.6, but apparently no explicit version of m-compiler-p is specified and it depends on maven used and falls-back to 3.1 here.

**Comment by arjantijms** [comment]
> https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#release - it's recognized since plugin 3.6, but apparently no explicit version of m-compiler-p is specified and it depends on maven used and falls-back to 3.1 here.

I thought, but clearly wrongly, that the compiler version came from the EE4J pom. But seems I was mistaken.

**Comment by pzygielo** [comment]
> I also thought this would set the correct version of the compiler of Maven 3.6.0, but also seemingly it does not actually do that. Probably need to upgrade the minimal Maven version a bit to that which has Maven compiler 3.6 at least.

That would be [maven 3.9.0](https://maven.apache.org/ref/3.9.0/maven-core/default-bindings.html), as all previous have m-c-p at 3.1.

Note: the [current GH runner ubuntu-latest](https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md) provides maven 3.8.8 only.

**Pull request merged**
