### PR TITLE
Fix #4727: UrlBuilder use & instead of =

### LINKED ISSUE #4727: URLBuilder: appendQueryString building invalid URL
While adding Client Window ID support to PrimeFaces a bug in Mojarra was discovered.
See: https://github.com/primefaces/primefaces/issues/6030

Basically Mojarra is building an incorrect URL for ClientWindowID like the screenshot below:
https://user-images.githubusercontent.com/10461942/85319612-10fea380-b4c2-11ea-8373-3d25a025ea05.png

This issue is right here: https://github.com/eclipse-ee4j/mojarra/blob/2d22f78f81548c10f2c48a8fd8a04caa1628c0b3/impl/src/main/java/com/sun/faces/context/UrlBuilder.java#L242

I will be submitting a PR to fix it.

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

**Comment by melloware** [comment]
I have signed the ECA now.

**Comment by hussainnm** [comment]
The first commit does not have Signed-off-by footer. You can amend your commits with Signed-off-by and force-push to pass the ECA.

Every commit needs a signed-off-by footer not just the last commit.

**Comment by melloware** [comment]
Can someone please guide me on how to fix this mess with the ECA?  I have signed it and I did "git commit -a -s" to my last commit but its still failing.

**Comment by hussainnm** [comment]
Check this video https://www.youtube.com/watch?v=YdJyJpT7rrs

**Comment by melloware** [comment]
figured it out but this is a nightmare and exactly the kind of thing that prevents developers from submitting PR's.  The fact they needed a 9 minute video because so many people have been having problems should be exactly the reason they should remove this.

**Pull request merged**
