### PR TITLE
#4881 Empty lists are discarded during state-saving

### PR DESCRIPTION
**Pull request by christophs78**
Compare with MyFaces BehaviorBase#restoreAttachedState as reference.
https://github.com/apache/myfaces/blob/master/api/src/main/java/jakarta/faces/component/behavior/BehaviorBase.java#L198

PrimeFaces-issues related to this PR:
primefaces/primefaces#7026
primefaces/primefaces#7181
primefaces/primefaces#6427

After this is merged we should do the same for master. (=4.0)

### CODE REVIEW

**Comment by christophs78** [comment]
@tandraschko Maybe you can add some feedback to this....
MyFaces works with _AttachedListStateWrapper to wrap lists during state-saving. Mojarra does not seem to have something similar.  What had been the reasons to introduce _AttachedListStateWrapper?

**Comment by tandraschko** [comment]
Out of my scope/history

**Comment by christophs78** [comment]
I tried to fix this within the existing Mojarra-codebase. 

Plan "B" would be to do it MyFaces-style. 
Look at BehaviorBase#restoreAttachedState as reference.
https://github.com/apache/myfaces/blob/master/api/src/main/java/jakarta/faces/component/behavior/BehaviorBase.java#L198

**Comment by tandraschko** [comment]
great work @christophs78 

@arjantijms i would be happy if such power users can be invited to be part of the Mojarra team ;)

**Comment by arjantijms** [comment]
@tandraschko absolutely!

@christophs78 if you're up to it, I'd absolutely like to nominate you to become Mojarra committer. What do you think?

**Review by arjantijms — APPROVED** [review]

**Comment by christophs78** [comment]
> @tandraschko absolutely!
> 
> @christophs78 if you're up to it, I'd absolutely like to nominate you to become Mojarra committer. What do you think?

Yes, please. We all have limited time budgets. I'm happy trying to find some time for core JSF and contribute to move JSF forward.

**Review by melloware — APPROVED** [review]

**Comment by arjantijms** [comment]
@tandraschko I can nominate you as regular committer first, after which I think you can already manage issues and labels and such. Whether you actually commit code or not beyond that is up to you, and of course not a requirement.

**Comment by tandraschko** [comment]
all right, thanks :)

**Pull request merged**
