### PR TITLE
Flash doPostPhaseActions() should be done before endDocument()

### PR DESCRIPTION
**Pull request by BalusC**
https://github.com/eclipse-ee4j/mojarra/issues/4977

### CODE REVIEW

**Comment by christophs78** [comment]
Looks good to me! Thanks for refactoring! (Tested it locally against PF Showcase and work´s as expected.)

Is there a chance to get 2.3.17 released before PrimeFaces 11.0.0? We´ll need it to have http://primefaces.org/showcase/ui/df/nested.xhtml working on Mojarra too.

**Comment by arjantijms** [comment]
> Is there a chance to get 2.3.17 released before PrimeFaces 11.0.0?

When is PrimeFaces 11 due to be released? It should be possible indeed.

**Comment by christophs78** [comment]
> > Is there a chance to get 2.3.17 released before PrimeFaces 11.0.0?
> 
> When is PrimeFaces 11 due to be released? It should be possible indeed.

Within the next few weeks. PF 11.0.0 RC2 was done about 3 weeks ago. @tandraschko do you know a exact release-date?

**Comment by arjantijms** [comment]
I staged 2.3.17 here: https://jakarta.oss.sonatype.org/content/repositories/staging/org/glassfish/jakarta.faces/2.3.17/

I executed the TCK against the 2.3 branch which passed.

**Comment by christophs78** [comment]
Many thanks @arjantijms & @BalusC !

**Pull request merged**
