### PR TITLE
Fixes #5298 - Mark 2.3 as EOL

### LINKED ISSUE #5298: Mark 2.3 as EOL
Proposal to update main README to reflect:

1. Faces 5.0 - under development
2. Faces 4.0 - stable release
3. Faces 3.0 - legacy release

And mark 2.3 as EOL

### PR DESCRIPTION
**Pull request by mnriem**

### CODE REVIEW

**Comment by melloware** [comment]
is 2.3 officially EOL?  Is there some guidelines for dates of EOL?

**Comment by mnriem** [comment]
@melloware As you can see in the PR and associated issue I proposed this as a way to move forward 3.0, 4.0 are out and 5.0 is under development so to me it makes sense to mark 2.3 as EOL. Now as this is an open source project you can step up to maintain 2.3 going forward ;)

**Comment by mnriem** [comment]
As for official guidance I think that is up to the committers of the project

**Comment by melloware** [comment]
Ok yep I was just curious because i think 2.3 is still the most widely used version as adoption of 4.0 will be slow as a lot of the large vendors like Red Hat don't even have official versions out yet supporting EE10.

**Pull request merged**
