### PR TITLE
Fix compilation on Java 11

### PR DESCRIPTION
**Pull request by lasombra**
This should fix issue #4461

### CODE REVIEW

**Comment by arjantijms** [comment]
Thanks for the PR! 

The ip-validation did fail though as you can see above. To clear it you have to create an Eclipse account, acknowledge the CLA there, and then kick off the check here again by pushing another commit.

**Comment by lasombra** [comment]
Ah, all set now.

**Comment by arjantijms** [comment]
Great, thanks again :)

**Comment by pzygielo** [comment]
Isn't [Signed-off-by entry](https://wiki.eclipse.org/Development_Resources/Contributing_via_Git#The_Commit_Record) required anymore?

**Comment by arjantijms** [comment]
Hmmm, you're right, the test should check for it, and normally not even allow to merge if signed-off is not correct. I'll revert the merge, just in case.

@lasombra Sorry for all the troubles, but can you commit once more and sign off the commit as explained here: https://wiki.eclipse.org/Development_Resources/Contributing_via_Git#The_Commit_Record

Thx!

**Comment by lasombra** [comment]
No problem @arjantijms. PR 4505 is up.

**Pull request merged**
