### PR TITLE
Fix for #4500

### PR DESCRIPTION
**Pull request by kalgon**
Fix for #4500

### CODE REVIEW

**Comment by kalgon** [comment]
Weird, I already signed the ECA for #3943 last year, do I need to do it again?

**Comment by pzygielo** [comment]
Didn't you get e-mail notification _IMPORTANT: Action Required - Update required to your Eclipse Contributor Agreement_? (It references [New Eclipse Foundation Committer and Contributor Agreements](https://blogs.eclipse.org/post/mike-milinkovich/new-eclipse-foundation-committer-and-contributor-agreements)).

**Comment by exsilium** [comment]
Any updated on this PR? Could we get this in? Thanks!

**Comment by codylerum** [comment]
I'm sure this is the furthest thing from the actual status of the project, but from the outside Mojarra seems to be stalled.

Multiple PRs over the last couple months have not had any comments from the project leads and that doesn't help to encourage contribution.

**Comment by juneau001** [comment]
@codylerum @exsilium Sorry for the silence, the project leads have been busy with other projects at this time.  As for myself, I've been working on other open source projects in my spare time right now as well, and hope to get back to Mojarra soon.  Mojarra is certainly not stalled...but cycles are just down for the time being.  I will try to jump in soon and try to assist in some of these areas.

**Comment by codylerum** [comment]
@juneau001 Thanks for the update! If there are ways we can assist please suggest.

**Comment by juneau001** [comment]
@codylerum You've done your part, I think...as you've nudged me!  I appreciate it.  I just need to find the time to look through the PRs and review.

**Comment by exsilium** [comment]
Thank you for the updates. Much appreciated!

**Comment by arjantijms** [comment]
>  but from the outside Mojarra seems to be stalled.

It has indeed stalled a little, but discussions have been going on. One of the reasons for stalling is a reduction in resources, and the other the ongoing debate in Jakarta on how we can (are allowed) to continue.

**Pull request merged**
