### PR TITLE
#1497+ #1498

### PR DESCRIPTION
**Pull request by tandraschko**

### CODE REVIEW

**Comment by tandraschko** [comment]
@arjantijms seems to work now :)

**Review by arjantijms — APPROVED** [review]
LGTM!

**Comment by arjantijms** [comment]
@tandraschko 
>  seems to work now :)

Finally :)

**Comment by tandraschko** [comment]
@arjantijms thanks :)

Could you please close: https://github.com/eclipse-ee4j/faces-api/issues/1497 and https://github.com/eclipse-ee4j/faces-api/issues/1498

**Pull request merged**
