### PR TITLE
Fixes #5357 - Move jakarta.faces-api Maven module to API project

### LINKED ISSUE #5357: Move jakarta.faces-api Maven module to API project

### PR DESCRIPTION
**Pull request by mnriem**
Depends on https://github.com/jakartaee/faces/issues/1856 and the SNAPSHOTs now being published to OSS Sonatype SNAPSHOT repository

### CODE REVIEW

**Review by BalusC — APPROVED** [review]

**Comment by BalusC** [comment]
LGTM but how do I re-run the build at all?

**Comment by mnriem** [comment]
@arjantijms Do you know if Eclipse Jenkins publishes to OSS Sonatype automatically?

**Comment by mnriem** [comment]
@BalusC Maybe for the time being I should add the API project as a git submodule so it is available during the build?

**Comment by mnriem** [comment]
@BalusC Added the Faces API as a git submodule so this now all builds fine. Let me know if you are OK with merging it like this? Thanks!

**Pull request merged**
