### PR TITLE
Fix #4082 Performance issue with ELUtils#isCompositeComponentMethodExprLookup

### LINKED ISSUE #4082: Performance issue with ELUtils#isCompositeComponentMethodExprLookup
On a complex page I hit a performance issue apparently caused by the regular expression-based methods in ELUtils that are used for classifying tag attributes:

isCompositeComponentLookupWithArgs
isCompositeComponentMethodExprLookup
isCompositeComponentExpr

These methods get called many hundreds of times on my page, and I suspect that the performance drop can be attributed mostly to a few way too long EL expressions.

With the attached naive caching of expressions I can cut the server-side rendering time of this page in half.

Since these methods are only called from TagAttributeImpl, I think that a cleaner solution would be to cache the results of these methods in three boolean fields in the TagAttributeImpl class itself - as is already being done for the result of ELUtils.isLiteral().

However this would require a small refactoring of the private (public?) method getValueExpression(FaceletContext ctx, String expr, Class type), since it can be called with any expression (not just the expression of the TagAttributeImpl). Thoughts?
#### Environment
Glassfish 3.1.2
#### Affected Versions
[2.1.6]

### PR DESCRIPTION
**Pull request by kguelzau**
storing Expression infos in TagAttributeImpl

Signed-off-by: Kai Gülzau <kguelzau@novomind.com>

### CODE REVIEW

**Comment by kguelzau** [comment]
@arjantijms is there any chance to merge this in the "near future"/this year?

**Comment by arjantijms** [comment]
Yes, that should be the idea indeed ;)

Apologies for not replying sooner. It's on my queue for review. Thanks for the reminder!

**Comment by kguelzau** [comment]
ping

**Comment by kguelzau** [comment]
can I do something to get this merged?

**Comment by juneau001** [comment]
I will try to take a look at this item soon.  I apologize for the delay.

**Comment by juneau001** [comment]
@kguelzau It looks like you need to sign the ECA before this change can be approved and merged.  If possible, please sign the committer agreement in order to proceed.  https://wiki.eclipse.org/Development_Resources/Handling_Git_Contributions

I appreciate your time and effort.

**Comment by kguelzau** [comment]
done

**Comment by kguelzau** [comment]
@arjantijms / @juneau001 this was merged to master (4.0) and was removed by the 3.0 merge with 8e87575b15a53b915705897768bd684ae2762500
Was this on purpose (e.g. not necessary anymore)?

**Comment by arjantijms** [comment]
@kguelzau Thanks for the eagle eyes here! It was a difficult merge, and we should manually update master again with this.

**Pull request merged**
