### PR TITLE
Remove unused imports

### PR DESCRIPTION
**Pull request by Emkas**
I've cleaned this type of warnings after importing project to Eclipse.

This is my first pull request in this project, so it more like exploring new ground.

### CODE REVIEW

**Comment by arjantijms** [comment]
Thanks a lot for your contribution! One thing that we need in order to accept it, is for you to accept the so-called ECA. This means creating an Eclipse account with the same email used for committing at https://www.eclipse.org, and from your profile page accepting the ECA.

**Comment by Emkas** [comment]
Hmmm... I've changed an e-mail in this commit and register on eclipse.org with the same e-mail address. Yet, I cannot accept ECA:

> Could not validate the users ECA sign-off status. Please ensure that the e-mail address of all contributing accounts match a valid Eclipse Foundation account with a valid ECA.

But an e-mail looks good: emilsierzega [at] gmail

**Comment by melloware** [comment]
I had a similar issue when I started with Mojarra and if I remember I had to update my commit with a signature after I signed the ECA.  I will try and find the command someone had me run

**Comment by melloware** [comment]
Here it is. I had to watch this video to fix mine

https://www.youtube.com/watch?v=YdJyJpT7rrs

**Comment by Emkas** [comment]
> I had a similar issue when I started with Mojarra and if I remember I had to update my commit with a signature after I signed the ECA. I will try and find the command someone had me run

Thanks for the tip!

It's OK now. My fault that I didn't read `CONTRIBUTING` more carefully :-)

**Review by melloware — APPROVED** [review]

**Pull request merged**
