### PR TITLE
Mojarra issue 5171

### PR DESCRIPTION
**Pull request by BalusC**
https://github.com/eclipse-ee4j/mojarra/issues/5171

### CODE REVIEW

**Comment by NicolaIsotta** [comment]
Hi @BalusC 
Testing locally I found out the fix can be simplified.
Adding this override to [ContextualCompositeValueExpression](https://github.com/eclipse-ee4j/mojarra/blob/8e87575b15a53b915705897768bd684ae2762500/impl/src/main/java/com/sun/faces/facelets/el/ContextualCompositeValueExpression.java):
```java
@Override
public ValueReference getValueReference(ELContext elContext) {

    FacesContext ctx = (FacesContext) elContext.getContext(FacesContext.class);
    boolean pushed = pushCompositeComponent(ctx);
    try {
        return originalVE.getValueReference(elContext);
    } finally {
        if (pushed) {
            popCompositeComponent(ctx);
        }
    }

}
```
InterceptingResolver in ValueExpressionAnalyzer is not needed anymore, so getReference can be simplified this way:
```java
public ValueReference getReference(ELContext elContext) {
    ValueReference reference = expression.getValueReference(elContext);
    if (reference != null) {
        Object base = reference.getBase();
        if (base instanceof CompositeComponentExpressionHolder) {
            ValueExpression ve = ((CompositeComponentExpressionHolder) base).getExpression(String.valueOf(reference.getProperty()));
            if (ve != null) {
                expression = ve;
                reference = getReference(elContext);
            }
        }
    }
    return reference;
}
```
I can make a PR if needed, let me know

**Comment by BalusC** [comment]
I'll adjust the PR and re-test when time allows me.

**Comment by BalusC** [comment]
Thank you very much, @NicolaIsotta , I've been able to get rid of the ValueExpressionAnalyzer completely with your insightful suggestion!

**Review by NicolaIsotta — APPROVED** [review]

**Comment by BalusC** [comment]
4.0 branch was split off from master after this PR was created but the PR wasn't updated to retarget 4.0.

New PR created for 4.0: https://github.com/eclipse-ee4j/mojarra/pull/5177

**Pull request merged**
