### PR TITLE
[Issue 4646] @PreDestroy not called all the times on view scoped using CDI

### PR DESCRIPTION
**Pull request by rmartinc**
Issue: #4646 

Finally we have reached the conclusion of preserving the current API and searching the view inside the list of the view maps if the old version is used. The two previous methods are deprecated and really not used inside the classes (just preserved in case something external is using them).

One test was added and checked in the 2.3 branch (no conflicts with master).  If you need any change just let us know.

Please take a look to the PR because we have a demanding customer behind this problem.

Thanks!

### CODE REVIEW

**Comment by fjuma** [comment]
@arjantijms Sorry to ping again, any chance you would be able to take a look at this one? (We have a Red Hat JBoss EAP customer that needs this fix.) Thanks!

**Comment by fjuma** [comment]
@arjantijms Alternatively, is there someone else who could take a look?

**Comment by fjuma** [comment]
@arjantijms Sorry to ping again, any chance you would be able to take a look at this one? (We have a Red Hat JBoss EAP customer that needs this fix.) Is there anyone else who would be able to approve this fix?

Thanks!

**Comment by bmaxwell** [comment]
@bshannon / @arjantijms - is there any one who can check/approve this fix?

**Comment by bshannon** [comment]
> @bshannon / @arjantijms - is there any one who can check/approve this fix?

Not me, I don't know this code at all, but I added a few other reviewers who might be able to help.

**Comment by codylerum** [comment]
@bshannon @arjantijms @BalusC @mnriem  It's a little concerning to see the complete lack of responsiveness on a PR from a large vendor like Redhat (Wildfly). I hate to push on this, but I know I'm not the only one watching from the outside and seeing the same.

Is Mojarra in some kind of limbo state where further development is disallowed?

**Comment by juneau001** [comment]
Hi Cody,

It has certainly been busy with the Jakarta EE 9 ramp up.  That said, I
will try to take a look at this PR very soon.

I apologize for the late communication.  I assure you that Mojarra is
certainly still moving forward.

Best Regards

Josh Juneau
juneau001@gmail.com
http://jj-blogger.blogspot.com
https://www.apress.com/us/search?query=Juneau
<https://www.apress.com/index.php/author/author/view/id/1866>

**Comment by arjantijms** [comment]
@codylerum 

It's heartbreaking for me to have Faces in this limbo, but the matter of the fact is that nobody from any vendor is working on this.  

I'm currently devoting the little free time I have to the various Jakarta projects, which for the last few months has been the Security Projects and GlassFish. Security is in the first waves of the Jakarta releases, Faces is last, hence why I've been postponing looking at Faces issues until the Security ones are done. 

If any vendor (Payara, Red Hat, IBM, ...) would like to propose people for this project to handle concerns such as this that would be more than welcome.

As the PR is not super trivial, I would need some time to look at it to okay it with confidence, but if Red Hat wants to vouch for its correctness I can always merge it it "blind" if really needed.

**Comment by codylerum** [comment]
@arjantijms Thanks for the update.

The state on this particular PR isn't critical for me as I'm deployed on Wildfly and will pick this up in their patched Mojarra in Wildfly 19.

It's just a little demoralizing for the community when they propose PR's and get little or no feedback on them for months and months. Hopefully things turn around and those with commit/review privileges have time to address things, or new capable parties are able to step up and become reviewers/committers.

Either way it's good just to have communication. Even if it's just to say that things will be paused for the next 6 months as it lets people know that Mojarra and JakartaEE in general hasn't completely stalled out.

**Comment by codylerum** [comment]
@rmartinc this should probably be a PR to the 2.3 branch right?

**Comment by rmartinc** [comment]
@codylerum This PR is sent to master but it can be applied to 2.3 too (no conflicts when I submitted it).

**Comment by fjuma** [comment]
@rmartinc This one has some conflicts that need to be fixed. Thanks!

**Comment by fjuma** [comment]
Just FYI, this PR has been submitted against master but we'll also need this to be merged to the 2.3 branch.

**Comment by arjantijms** [comment]
As some files have moved in the meantime, this can only easily be merged in two steps. I'll merge it in as-is, and the do a follow-up commit for the merge.

**Pull request merged**
