### PR TITLE
Support new FacesMessage.Severity.SUCCESS in h:message/h:messages

### PR DESCRIPTION
**Pull request by BalusC**
https://github.com/eclipse-ee4j/mojarra/issues/5489

Associated PR in Faces side: https://github.com/jakartaee/faces/pull/1964

### CODE REVIEW

**Comment by mnriem** [comment]
I would rather see Severity.NONE instead of SUCCESS.

**Comment by BalusC** [comment]
That's not what was requested by community https://github.com/jakartaee/faces/issues/1592.

**Comment by mnriem** [comment]
I realize that, but it seems an odd fit.

Or asking a nice LLM to explain message severity and "SUCCES" to me:

'In the context of message severity, “SUCCESS” is generally not considered a severity level. Severity levels typically indicate the urgency or criticality of an issue, ranging from emergency situations to debug information. “SUCCESS” is more of a status or outcome, indicating that an operation or process completed as intended without errors'

**Comment by BalusC** [comment]
Please continue in https://github.com/jakartaee/faces/issues/1592

**Pull request merged**
