### PR TITLE
Clarified javadoc wrt 'if' attribute and fixed wrong attr name in vdldoc

### PR DESCRIPTION
**Pull request by BalusC**
https://github.com/jakartaee/faces/issues/1811

### CODE REVIEW

**Comment by BalusC** [comment]
cc: @tandraschko

**Comment by BalusC** [comment]
@tandraschko and/or @arjantijms can you please review/approve this?

**Comment by tandraschko** [comment]
+1

**Review by arjantijms — APPROVED** [review]

**Comment by volosied** [comment]
@tandraschko 

MyFaces Docs show `rendered`, not `if`: 
image

**Pull request merged**
