### PR TITLE
Proposed resolution for issue #4649

### LINKED ISSUE #4649: ExternalContext.redirect() for AJAX creates a new HttpSession and may throw a ClassCastException/NullPointerException
Hello,

I already submitted an issue on the old [javaserverfaces repo](https://github.com/javaserverfaces/mojarra/issues/4405), so I'm also reporting the same thing here.

this problem has been discussed on [StackOverflow](https://stackoverflow.com/questions/58537251/jsf-mojarra-externalcontext-redirect-creates-a-httpsession)

the code of `redirect()`:

    @Override
    public void redirect(String requestURI) throws IOException {

        FacesContext ctx = FacesContext.getCurrentInstance();
        doLastPhaseActions(ctx, true);

        if (ctx.getPartialViewContext().isPartialRequest()) {
            if (getSession(true) instanceof HttpSession &&    // <----- creates a new HttpSession
                ctx.getResponseComplete()) {
                throw new IllegalStateException();
            }
            PartialResponseWriter pwriter;
            ResponseWriter writer = ctx.getResponseWriter();
            if (writer instanceof PartialResponseWriter) {
                pwriter = (PartialResponseWriter) writer;
            } else {
                pwriter = ctx.getPartialViewContext().getPartialResponseWriter();
            }
            setResponseContentType("text/xml");
            setResponseCharacterEncoding("UTF-8");
            addResponseHeader("Cache-Control", "no-cache");
    //        pwriter.writePreamble("<?xml version='1.0' encoding='UTF-8'?>\n");
            pwriter.startDocument();
            pwriter.redirect(requestURI);
            pwriter.endDocument();
        } else {
            ((HttpServletResponse) response).sendRedirect(requestURI);  // <----- may throw a ClassCastException/NullPointerException
        }
        ctx.responseComplete();       
    }

As you can see there are two problems.

It should be replaced with something like:

    @Override
    public void redirect(String requestURI) throws IOException {

        FacesContext ctx = FacesContext.getCurrentInstance();
        doLastPhaseActions(ctx, true);

        if (ctx.getPartialViewContext().isPartialRequest()) {
            if (response instanceof HttpServletResponse &&
                ctx.getResponseComplete()) {
                throw new IllegalStateException();
            }
            PartialResponseWriter pwriter;
            ResponseWriter writer = ctx.getResponseWriter();
            if (writer instanceof PartialResponseWriter) {
                pwriter = (PartialResponseWriter) writer;
            } else {
                pwriter = ctx.getPartialViewContext().getPartialResponseWriter();
            }
            setResponseContentType("text/xml");
            setResponseCharacterEncoding("UTF-8");
            addResponseHeader("Cache-Control", "no-cache");
    //        pwriter.writePreamble("<?xml version='1.0' encoding='UTF-8'?>\n");
            pwriter.startDocument();
            pwriter.redirect(requestURI);
            pwriter.endDocument();
        } else if (response instanceof HttpServletResponse) {
            ((HttpServletResponse) response).sendRedirect(requestURI);
        } else {
            throw new IllegalStateException();
        }
        
        ctx.responseComplete();
    }

### PR DESCRIPTION
**Pull request by mmariotti**
Simple code changes to resolve #4649

### CODE REVIEW

**Comment by arjantijms** [comment]
I know this is a very old PR, but we can't merge it because of the failing ECA check. You can make pass by creating an Eclipse account (using the same email as used here) and accepting the ECA.

**Comment by mmariotti** [comment]
I linked this github account with the email address used when subscribed ECA.
This should be enuogh to merge. 
Conversely, let me know!

**Comment by mmariotti** [comment]
Nope, this does not work for "Signed-off-by".
I can't checkout to amend commits until next week (no dev env available), please feel free to move the edited lines directly into the master branch.

**Comment by BalusC** [comment]
PR redone via https://github.com/eclipse-ee4j/mojarra/pull/4899

**Pull request closed without merging**
