### PR TITLE
[Issue 4677] IdMapper can create repeated ids in clustered environments

### PR DESCRIPTION
**Pull request by rmartinc**
Fix for #4677. The idea is using a new context parameter that removes the IdMapper and uses the facelet ID directly.

### CODE REVIEW

**Comment by fjuma** [comment]
@rmartinc This one has some conflicts that need to be fixed. Thanks!

**Comment by fjuma** [comment]
Just FYI, this PR has been submitted against master but we'll also need this to be merged to the 2.3 branch.

**Comment by BalusC** [comment]
Next time please create PR for 2.3 branch if problem is initially present in 2.3 branch.

**Comment by BalusC** [comment]
PR has aged, I've recreated for 2.3: https://github.com/eclipse-ee4j/mojarra/pull/4900/files

**Pull request closed without merging**
