### PR TITLE
[Issue 4652] Memory leak in FlashScope when response is already commi…

### PR DESCRIPTION
**Pull request by spyrkob**
…tted

Issue: https://github.com/eclipse-ee4j/mojarra/issues/4652

### CODE REVIEW

**Comment by spyrkob** [comment]
@arjantijms could you take a look at this please? It's an edge case #4633 didn't catch.

**Comment by spyrkob** [comment]
Hi @arjantijms, we have a Red Hat JBoss EAP customer running into this issue and needing a fix. Would you be able to review if the change looks good? Thanks a lot!

**Comment by fjuma** [comment]
@arjantijms Sorry to ping again, any chance you would be able to take a quick look at this one? (We have a Red Hat JBoss EAP customer that needs this fix so just want to make sure that you approve so we can get the fix into our fork.) Thanks!

**Comment by bmaxwell** [comment]
@arjantijms , we have verified this proposed fix resolves the memory leak, so just need a check and approval to merge.  Thanks!

**Comment by bmaxwell** [comment]
@bshannon / @arjantijms - is there any one who can check/approve this fix?

**Comment by bshannon** [comment]
> @bshannon / @arjantijms - is there any one who can check/approve this fix?

Not me, I don't know this code at all, but I added a few other reviewers who might be able to help.

**Comment by fjuma** [comment]
Just FYI, this PR has been submitted against master but we'll also need this to be merged to the 2.3 branch.

**Review by arjantijms — APPROVED** [review]

**Pull request merged**
